url: https://vl4d.github.io
baseurl: http://vldmr.info
#dev-baseurl: /vldmr.io/

# Site settings
title: Vladimir S. Murray
email: murray.vladimir@gmail.com
description: Personal site and portfolio for Vladimir Murray

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2EB8E6
  secondary: 248FB2
  secondary-dark: 333

# Team names, titles and social links
personal:
  name: Vladimir S. Murray
  qualification: BSc. Computer Science
  pic: avatar
  position: Software Developer | Consultant

#Navbar items
navbar:
  - title: Skills
    anchor: skills
  - title: Experience
    anchor: experience
  - title: Portfolio
    anchor: portfolio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://jm.linkedin.com/in/vsmurray
  - title: github
    url: http://github.com/vl4d
  - title: twitter
    url: http://twitter.com/vl4dism
  - title: google-plus
    url: https://plus.google.com/+VladimirMurrayTech

# Build settings
markdown: kramdown
permalink: pretty
