url: https://vl4d.github.io
baseurl: http://vldmr.info

# Site settings
title: Vladimir S. Murray
email: murray.vladimir@gmail.com
description: "Personal site and portfolio for Vladimir Murray"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
personal:
  name: Vladimir S. Murray
  pic: 1
  position: Software Developer|Consultant

#Navbar items
navbar:
  - title: Skills
    anchor: skills
  - title: Education
    anchor: education
  - title: Portfolio
    anchor: portfolio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/vl4dism
  - title: linkedin
    url: https://www.facebook.com/vladimir.murray
  - title: github
    url: http://github.com/vl4d
  - title: google-plus
    url: #

# Build settings
markdown: kramdown
permalink: pretty